name: SYNC DEVICE TEST
 
on:

   push:

     branches: [ master ]

   pull_request:

     branches: [ master ]
 
jobs:

   build:
 
    runs-on: ubuntu-latest
 
    steps:

     - uses: actions/checkout@v2
       
     - name: sync test build
       run: g++ -o synctest testsyncdevices/*.cpp
      
     - name: Run synctest
       run: ./synctest
